// Generated by CoffeeScript 1.6.1
(function() {
  var $, $calendar, onClickDay, onClickListViewBtn, onHoverListViewBtn;

  $ = jQuery;

  $calendar = $("#calendar");

  onClickDay = function(date, allDay) {
    var d, fc, start, t;
    fc = $.fullCalendar;
    d = fc.formatDate(date, $L("default.format.date"));
    t = fc.formatDate(date, $L("default.format.time"));
    start = encodeURIComponent("" + d + " " + t);
    allDay = encodeURIComponent(String(allDay));
    return window.location.href = $calendar.data("create-event-url") + ("?start=" + start + "&allDay=" + allDay);
  };

  onClickListViewBtn = function() {
    return window.location.href = $calendar.data("list-view-url");
  };

  onHoverListViewBtn = function() {
    return $(this).toggleClass("ui-state-hover");
  };

  $calendar.fullCalendar({
    allDayText: $L("calendarEvent.allDay.label"),
    axisFormat: $L("calendarEvent.axis.format"),
    buttonText: $L("calendarEvent.button.text"),
    columnFormat: $L("calendarEvent.column.format"),
    dayClick: onClickDay,
    dayNames: $L("weekdaysLong"),
    dayNamesShort: $L("weekdaysShort"),
    defaultView: $calendar.data("current-view"),
    eventSources: [
      {
        url: $calendar.data("load-events-url")
      }
    ],
    firstDay: $L("calendarFirstDay"),
    isRTL: $L("calendarRTL"),
    header: {
      center: "title",
      left: "prev,next today",
      right: "agendaDay,agendaWeek,month"
    },
    monthNames: $L("monthNamesLong"),
    monthNamesShort: $L("monthNamesShort"),
    theme: true,
    timeFormat: $L("calendarEvent.time.format"),
    titleFormat: $L("calendarEvent.title.format")
  });

  $(".fc-header-right").append("<span class=\"fc-button fc-button-list ui-state-default ui-corner-right\">\n  <span class=\"fc-button-inner\">\n    <span class=\"fc-button-content\">" + ($L('calendarEvent.button.text.list')) + "</span>\n    <span class=\"fc-button-effect\"></span>\n  </span>\n</span>");

  $(".fc-button-month").removeClass("ui-corner-right");

  $(".fc-button-list").on("click", onClickListViewBtn).on("hover", onHoverListViewBtn);

}).call(this);
