// Generated by CoffeeScript 1.6.1
(function() {
  var $, $accessCodeInput, $generateAccessCodeBtn, generateAccessCode;

  $ = jQuery;

  $accessCodeInput = $("#accessCode");

  $generateAccessCodeBtn = $("#generate-access-code");

  generateAccessCode = function(length) {
    var c, i, n, s, _i;
    if (length == null) {
      length = 6;
    }
    s = "";
    for (i = _i = 1; 1 <= length ? _i <= length : _i >= length; i = 1 <= length ? ++_i : --_i) {
      if (Math.random() < 0.5) {
        n = Math.floor(Math.random() * 10);
        c = String(n);
      } else {
        n = Math.floor(Math.random() * 26 + 65);
        c = String.fromCharCode(n);
      }
      s += c;
    }
    return s;
  };

  $("#organization").autocompleteex({
    select: function(event, ui) {
      var $name;
      $name = $("#name");
      if (!$name.val()) {
        return $name.val(ui.item.label);
      }
    }
  });

  $generateAccessCodeBtn.on("click", function() {
    return $accessCodeInput.val(generateAccessCode());
  });

  if (!$accessCodeInput.val()) {
    $generateAccessCodeBtn.triggerHandler("click");
  }

}).call(this);
