// Generated by CoffeeScript 1.6.1
(function() {
  var $;

  $ = jQuery;

  $("#organization").autocompleteex();

  $("#person").autocompleteex({
    loadParameters: function() {
      return {
        organization: $("#organization\\.id").val()
      };
    }
  });

}).call(this);
