// Generated by CoffeeScript 1.6.1
(function() {
  var $, $recType, initRecTypes, onClickRecType;

  $ = jQuery;

  $recType = $("#recType");

  initRecTypes = function() {
    var $this;
    $this = $(this);
    if ($recType.val() & $this.val()) {
      return $this.attr("checked", true);
    }
  };

  onClickRecType = function() {
    var $rt, $this;
    $rt = $recType;
    $this = $(this);
    if (this.checked) {
      $rt.val($rt.val() | $this.val());
    } else {
      $rt.val($rt.val() & ~$this.val());
    }
    return true;
  };

  $("#addresses").addrfields({
    leftPrefix: "billingAddr",
    menuItems: [
      {
        action: "clear",
        side: "left",
        text: $L("organization.billingAddr.clear")
      }, {
        action: "copy",
        side: "left",
        text: $L("organization.billingAddr.copy")
      }, {
        action: "clear",
        side: "right",
        text: $L("organization.shippingAddr.clear")
      }, {
        action: "copy",
        side: "right",
        text: $L("organization.shippingAddr.copy")
      }
    ],
    rightPrefix: "shippingAddr"
  });

  $(".rec-type").on("click", onClickRecType).each(initRecTypes);

}).call(this);
