// Generated by CoffeeScript 1.6.1
(function() {
  var $, $picture;

  $ = jQuery;

  $("#organization").autocompleteex();

  $picture = $("#picture");

  $picture.lightbox({
    imgDir: $picture.data("img-dir")
  });

  $(".document-delete").on("click", function() {
    $ = jQuery;
    $("#pictureRemove").val(1);
    return $(".document-preview").add(".document-preview-links").remove();
  });

  $("#addresses").addrfields({
    leftPrefix: "mailingAddr",
    menuItems: [
      {
        action: "clear",
        side: "left",
        text: $L("person.mailingAddr.clear")
      }, {
        action: "copy",
        side: "left",
        text: $L("person.mailingAddr.copy")
      }, {
        action: "loadFromOrganization",
        propPrefix: "billingAddr",
        side: "left",
        text: $L("person.addr.fromOrgBillingAddr")
      }, {
        action: "loadFromOrganization",
        propPrefix: "shippingAddr",
        side: "left",
        text: $L("person.addr.fromOrgShippingAddr")
      }, {
        action: "clear",
        side: "right",
        text: $L("person.otherAddr.clear")
      }, {
        action: "copy",
        side: "right",
        text: $L("person.otherAddr.copy")
      }, {
        action: "loadFromOrganization",
        propPrefix: "billingAddr",
        side: "right",
        text: $L("person.addr.fromOrgBillingAddr")
      }, {
        action: "loadFromOrganization",
        propPrefix: "shippingAddr",
        side: "right",
        text: $L("person.addr.fromOrgShippingAddr")
      }
    ],
    organizationId: "#organization\\.id",
    rightPrefix: "otherAddr"
  });

}).call(this);
