// Generated by CoffeeScript 1.6.1
(function() {
  var $, changePhase, loadList, onChangeProjectPhase, onChangeTopCheckbox, onChangeType, onClickAddBtn, onClickLink, onClickSelectItem, onCreateProjectItem, onDeleteProjectItem, onOpenSelectDlg, onSelectProjectItem, onSelectProjectStatus, onSubmittedSelectedItems, showFileSelector, submitSelectedDocuments, submitSelectedItems;

  $ = jQuery;

  changePhase = function(phaseName) {
    $ = jQuery;
    return $.get($("#project-phases").data("set-phase-url"), {
      phase: phaseName
    });
  };

  loadList = function(url) {
    var data, search;
    $ = jQuery;
    if (url == null) {
      url = $("#select-project-item-type-selector :selected").val();
    }
    data = {
      view: "selector"
    };
    search = $("#selector-search").val();
    if (search) {
      data.search = search;
    }
    return $("#select-project-item-list").load(url, data);
  };

  onChangeProjectPhase = function() {
    var $section, $this;
    $ = jQuery;
    $this = $(this);
    $("#project-phase").text($this.text());
    $section = $this.parents("section");
    $section.addClass("current").siblings().removeClass("current");
    changePhase($section.data("phase"));
    return false;
  };

  onChangeTopCheckbox = function() {
    var $this;
    $this = $(this);
    return $this.parents(".content-table").find("tbody td:first-child input:checkbox").attr("checked", $this.is(":checked"));
  };

  onChangeType = function() {
    var $dlg, $option, $this;
    $ = jQuery;
    $dlg = $("#select-project-item-dialog");
    $this = $(this);
    $option = $this.find(":selected");
    $dlg.find("h2").text($option.text());
    if ($option.data("controller") === "document") {
      showFileSelector($this.val());
      $dlg.find(".search-field").add(".submit-field", $dlg).add("#select-project-item-list").hide();
      return $dlg.find(".filler").add("#select-project-document-list").show();
    } else {
      $("#selector-search").val("");
      loadList($this.val());
      $dlg.find(".search-field").add(".submit-field", $dlg).add("#select-project-item-list").show();
      return $dlg.find(".filler").add("#select-project-document-list").hide();
    }
  };

  onClickAddBtn = function() {
    var ids;
    $ = jQuery;
    ids = [];
    $("#select-project-item-list tbody :checked").each(function() {
      return ids.push($(this).parents("tr").data("item-id"));
    });
    submitSelectedItems(ids);
    $("#select-project-item-dialog").dialog("close");
    return false;
  };

  onClickLink = function() {
    loadList($(this).attr("href"));
    return false;
  };

  onClickSelectItem = function(event) {
    var itemId;
    $ = jQuery;
    event.stopImmediatePropagation();
    itemId = $(this).parents("tr").data("item-id");
    submitSelectedItems([itemId]);
    $("#select-project-item-dialog").dialog("close");
    return false;
  };

  onCreateProjectItem = function() {
    var phaseName;
    $ = jQuery;
    phaseName = $(this).parents("section").data("phase");
    $("#create-project-item-dialog").dialog({
      modal: true
    }).find("a").click(function() {
      window.location.href = "" + ($(this).attr('href')) + "&projectPhase=" + phaseName;
      return false;
    });
    return false;
  };

  onDeleteProjectItem = function() {
    var $this;
    $ = jQuery;
    $this = $(this);
    if ($.confirm($L("default.delete.confirm.msg"))) {
      $.get($this.attr("href"), null, function() {
        return $this.closest("li").remove();
      });
    }
    return false;
  };

  onOpenSelectDlg = function() {
    $ = jQuery;
    $(this).find(".filler").hide();
    return $("#select-project-item-type-selector").trigger("change");
  };

  onSelectProjectItem = function() {
    var phaseName;
    $ = jQuery;
    phaseName = $(this).parents("section").data("phase");
    $("#select-project-item-dialog").dialog({
      minWidth: 900,
      minHeight: 520,
      modal: true,
      open: onOpenSelectDlg
    }).data("phase", phaseName);
    return false;
  };

  onSelectProjectStatus = function() {
    var $this, status;
    $this = $(this);
    status = $this.val();
    $.get($this.data("submit-url"), {
      status: status
    });
    return $("#project-status-indicator").attr("class", "project-status-" + status).text($this.find(":selected").text());
  };

  onSubmittedSelectedItems = function() {
    return window.location.reload(true);
  };

  showFileSelector = function(url) {
    return $("#select-project-document-list").elfinder({
      commands: ["open", "reload", "home", "up", "back", "forward", "getfile", "quicklook", "download", "rm", "duplicate", "rename", "mkdir", "mkfile", "upload", "copy", "cut", "paste", "edit", "search", "info", "view", "help", "sort"],
      commandsOptions: {
        getfile: {
          onlyURL: false
        }
      },
      contextmenu: {
        files: ["getfile", "|", "open", "quicklook", "|", "download", "|", "copy", "cut", "paste", "duplicate", "|", "rm", "|", "edit", "rename", "|", "info"]
      },
      getFileCallback: submitSelectedDocuments,
      lang: "de",
      uiOptions: {
        toolbar: [["back", "forward"], ["mkdir", "mkfile", "upload"], ["open", "download", "getfile"], ["info", "quicklook"], ["copy", "cut", "paste"], ["rm"], ["duplicate", "rename", "edit"], ["search"], ["view", "sort"], ["help"]]
      },
      url: url
    }).elfinder("instance");
  };

  submitSelectedDocuments = function(file) {
    var $dialog;
    $ = jQuery;
    $dialog = $("#select-project-item-dialog");
    return $.post($dialog.data("submit-url"), {
      projectPhase: $dialog.data("phase"),
      controllerName: "document",
      documents: file.hash
    }, onSubmittedSelectedItems);
  };

  submitSelectedItems = function(ids) {
    var $dialog;
    $ = jQuery;
    $dialog = $("#select-project-item-dialog");
    return $.post($dialog.data("submit-url"), {
      projectPhase: $dialog.data("phase"),
      controllerName: $("#select-project-item-type-selector :selected").data("controller"),
      itemIds: ids.join()
    }, onSubmittedSelectedItems);
  };

  $("#project-phases").on("click", "h4", onChangeProjectPhase).on("click", ".project-phase-actions-create", onCreateProjectItem).on("click", ".project-phase-actions-select", onSelectProjectItem).on("click", ".item-delete-btn", onDeleteProjectItem);

  $("#project-status").selectBoxIt({
    theme: "jqueryui"
  }).change(onSelectProjectStatus);

  $("#select-project-item-dialog").on("click", ".search-btn", function() {
    return loadList();
  }).on("click", "#select-project-item-add-btn", onClickAddBtn).on("change", "#select-project-item-type-selector", onChangeType);

  $("#select-project-item-list").on("change", ".content-table th input:checkbox", onChangeTopCheckbox).on("click", ".content-table tbody a", onClickSelectItem).on("click", "a", onClickLink);

}).call(this);
