#
# application.yml
#
# Copyright (c) 2011-2016, Daniel Ellermann
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#


---
grails:
    profile: web
    codegen:
        defaultPackage: org.amcworld.springcrm
    gorm:
        # Whether to autowire entities.
        # Disabled by default for performance reasons.
        autowire: false
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
    spring:
        transactionManagement:
            proxies: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
        buildNumber: '@info.app.buildNumber@'
        buildDate: '@info.app.buildDate@'
spring:
    groovy:
        template:
            check-template-location: false
    main:
        banner-mode: "off"

# Spring Actuator Endpoints are disabled by default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
                - text/html
                - application/xhtml+xml
            js: text/javascript
            json:
                - application/json
                - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
                - application/hal+json
                - application/hal+xml
            xml:
                - text/xml
                - application/xml
    # XXX does not work in Grails 3.1.4
    # web:
    #     url:
    #         converter: hyphenated
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
        upload:
            maxFileSize: 5242880
            maxRequestSize: 5242880
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
            sitemesh:
                preprocess: true
endpoints:
    jmx:
        unique-names: true

---
grails:
    gorm:
        failOnError: false
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        # cache.provider_class: 'net.sf.ehcache.hibernate.EhCacheProvider'
        region.factory_class: 'org.hibernate.cache.ehcache.EhCacheRegionFactory'
        format_sql: true

endpoints:
    jmx:
        unique-names: true


---
#================================================
#
# Data source configuration
#
#================================================

#
# Use docker for a mongodb database:
# docker run --name mongo-test -p 27017:27017 -d mongo
#
# In order to connect using mongoshell use:
# docker run -it --link mongo-test:mongo --rm \
#   mongo sh -c 'exec mongo \
#   "$MONGO_PORT_27017_TCP_ADDR:$MONGO_PORT_27017_TCP_PORT/springcrm"'
grails:
    mongodb:
        port: 27017
        databaseName: springcrm
        engine: codec
        default:
            mapping:
                version: false

environments:
    development:
        grails:
            mongodb:
                host: localhost
    production:
        grails:
            mongodb:
                host: mongodb

---
#================================================
#
# Asset configuration
#
#================================================

grails:
    assets:
        excludes:
            # stylesheets
            - bootstrap/**.scss
            - font-awesome/**.scss
            - js-calc/**.scss
            - selectize/**.scss
            - vat-calc/**.scss

            # scripts
            - bootstrap/*.js
            - jquery/*.js
            - jqueryui/*.js
            - polyfilles/*.js
            - selectize/*.js
            - widgets/**

---
#================================================
#
# Plugin configuration
#
#================================================

markdown:
    abbreviations: true
    definitionLists: true
    hardwraps: true
    removeHtml: true
    smartPunctuation: true
    tables: true

---
#================================================
#
# SpringCRM configuration
#
#================================================

springcrm:
    cacheDocs: true
    dir:
        base: ${user.home}/.springcrm
        data: ${springcrm.dir.base}/data
        database: ${springcrm.dir.base}/database
        documents: ${springcrm.dir.base}/documents
        installer: ${springcrm.dir.base}/install
        log: ${springcrm.dir.base}/log
        print: ${springcrm.dir.base}/print
    lruList:
        numEntries: 10
    mail:
        from: SpringCRM Service <noreply@springcrm.de>

environments:
    test:
        springcrm:
            dir:
                base: ${java.io.tmpdir}/springcrm
                data: ${springcrm.dir.base}/data
                documents: ${springcrm.dir.base}/documents
                installer: ${springcrm.dir.base}/install
                log: ${springcrm.dir.base}/log
                print: ${springcrm.dir.base}/print


---
#================================================
#
# Documentation configuration
#
#================================================

grails:
    doc:
        title: SpringCRM
        authors:
            - Daniel Ellermann <d.ellermann@amc-world.de>
        license: GPL v3


---
#================================================
#
# Plugin settings
#
#================================================

grails:
    plugin:
        springsecurity:
            authority:
                className: org.amcworld.springcrm.Role
                groupAuthorityNameField: authorities
            controllerAnnotations:
                staticRules:
                    - pattern: /
                      access:
                          - permitAll
                    - pattern: /error
                      access:
                          - permitAll
                    - pattern: /assets/**
                      access:
                          - permitAll
                    - pattern: /help/**
                      access:
                          - permitAll
                    - pattern: /install/**
                      access:
                          - permitAll
                    - pattern: /**/favicon.ico
                      access:
                          - permitAll
            filterChain:
                chainMap:
                    - pattern: /assets/**
                      filters: none
                    - pattern: /**/favicon.ico
                      filters: none
                    - pattern: /**
                      filters: JOINED_FILTERS
            logout:
                afterLogoutUrl: /
            printStatusMessages: false
            userLookup:
                userDomainClassName: org.amcworld.springcrm.User
            useRoleGroups: true

environments:
    development:
        grails:
            plugin:
                fields:
                    disableLookupCache: true
