#
# application.yml
#
# Copyright (c) 2011-2016, Daniel Ellermann
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#


---
grails:
    profile: web
    codegen:
        defaultPackage: org.amcworld.springcrm
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
        buildNumber: '@info.app.buildNumber@'
        buildDate: '@info.app.buildDate@'
spring:
    groovy:
        template:
            check-template-location: false

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    # XXX does not work in Grails 3.1.4
    # web:
    #     url:
    #         converter: hyphenated
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html      # TODO was 'none' in old config
                taglib: none
                staticparts: none
            sitemesh:
                preprocess: true
---
grails:
    gorm:
        failOnError: false
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        # cache.provider_class: 'net.sf.ehcache.hibernate.EhCacheProvider'
        region.factory_class: 'org.hibernate.cache.ehcache.EhCacheRegionFactory'
        format_sql: true

endpoints:
    jmx:
        unique-names: true

dataSource:
    dbCreate: none    # updated by database-migration plugin
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password:

environments:
    development:
        dataSource:
            driverClassName: com.mysql.jdbc.Driver
            # url: jdbc:mysql://localhost/springcrm?autoreconnect=true
            url: jdbc:mysql://localhost/springcrm2
            username: 'project'
            password: 'haluni21'
            properties:
                dbProperties:
                    autoReconnect: true
                    characterEncoding: UTF-8
                    useUnicode: true
            # logSql: true

    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            dbunitXmlType: flat
            jndiName: null
            properties:
                initSQL: SET REFERENTIAL_INTEGRITY FALSE

    production:
        dataSource:
            jndiName: java:comp/env/jdbc/springcrmDataSource

    standalone:
        dataSource:
            properties:
                initSQL: SET REFERENTIAL_INTEGRITY FALSE
---
grails:
    assets:
        excludes:
            # stylesheets
            - bootstrap/**.less
            - font-awesome/**.less
            - js-calc/**.less
            - selectize/**.less
            - vat-calc/**.less

            # scripts
            - bootstrap/*.js
            - jquery/*.js
            - jqueryui/*.js
            - selectize/*.js
            - widgets/**
        less:
            compiler: standard
